[package]
name = "solidity-backend-comparer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.35", features = ["derive"] }
csv = "1.3.1"
itertools = "0.14.0"
rtlola-streamir-interpreter = "0.1.0"
rtlola-streamir = "0.1.0"